name: pre-merge-workflow
on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: A job to run all the java unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # need to build so that test module has the target directory to use the JAR from
      - name: Validate and Build
        run: mvn -B clean package --file pom.xml -DskipTests
      - name: Run Unit Tests
        run: mvn -B package --file pom.xml